---
name: Code quality gate

pool:
  vmImage: ubuntu-20.04

jobs:
  - job: QualityChecks
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"
        displayName: Set python version
      - script: |
          pip install -r requirements-code-quality.txt
          az config set bicep.use_binary_from_path=false
          az bicep install
        displayName: Installing code quality dependencies
        workingDirectory: $(Build.SourcesDirectory)
      - script: |
          pre-commit run --all-files
        displayName: Run quality gate
        workingDirectory: $(Build.SourcesDirectory)
      # - task: Bash@3
      #   inputs:
      #     targetType: 'inline'
      #     script: |
      #         #!/bin/bash
      #         result=$(find . ! -name "GitVersion.yml" -type f -name "*.yml")
      #         echo $result
      #         if [ ${#result} -ge 5 ]; then echo "the repo contains .yml files, please correct!" ; exit 1
      #         else echo "the repo does not contain .yml files"
      #         fi
      #     workingDirectory: '$(Build.SourcesDirectory)'
